services:
    messenger-redis:
        image: redis:8
        container_name: redis
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        environment:
            - REDIS_PASSWORD=$REDIS_PASSWORD
        healthcheck:
            test: ["CMD-SHELL", "redis-cli -a $$REDIS_PASSWORD PING | grep -q PONG"]
            interval: 20s
            timeout: 10s
            retries: 3
            start_period: 20s

    messenger-postgres:
        image: postgres:16
        container_name: postgres-messenger
        restart: always
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_DB: $POSTGRES_DB
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
            interval: 20s
            timeout: 10s    
            retries: 3
            start_period: 20s
    
    messenger-api:
        build: 
            context: .
            dockerfile: backend/api/Dockerfile
        hostname: messenger-api
        restart: on-failure
        ports:
            - '8080:8080'
        depends_on:
            messenger-postgres:
                condition: service_healthy
                restart: true
            messenger-redis:
                condition: service_healthy
                restart: true


volumes:
    redis-data:
        driver: local
    postgres-data:
        driver: local